name: Node.js 

on:
   push:
     branches: 
     - main
     pull_request:
   branches: 
   - main

jobs:
    build:

runs-on: ubuntu-latest

strategy:
  matrix:
node-version: [20.x]

steps:
- name: Checkout respiratory
  uses: actions/checkout@v3
  
  -name: set up Node.j
  uses: actions/setup-node@v3
  with:
   node-version: ${{matrix.node-version}}

   
-name: install dependances
run: npm install

 -name: Start application
 run: npm start

